coverage:
  paths:
    - coverage/.resultset.json
  # acceptable: 60% # カバレッジがこの数値を下回るとCIがfailする
comment: # レポート内容をコメント投稿設定
  if: is_pull_request # PRの場合のみコメントを投稿する
  hideFooterLink: true # フッターのoctocovのリンクを非表示
# report: # レポートの出力設定
#   datastores:
#     - artifact://${GITHUB_REPOSITORY} # レポートの出力先（GitHub ActionsのArtifactsに保存する）
# diff:
#   datastores:
#     - artifact://${GITHUB_REPOSITORY}