version: '3'
services:
  db:
    image: postgres:11.2-alpine
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 8080"
    environment:
      WEBPACKER_DEV_SERVER_HOST: "0.0.0.0"
      RAILS_SERVE_STATIC_FILES: "1"
      EDITOR: "vim"
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  postgres_volume:
