name: Rspec

on:
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Ruby 3.2.2, Node 18の環境をセットアップ
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Setup database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
          bundle exec rails db:migrate

      - name: Exec rspec
        run: bundle exec rspec
      # octocovによりカバレッジレポートをPRコメントで表示
      - name: Coverage Report by octocov (in this pull request)
        uses: k1LoW/octocov-action@v0
